---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-sys-jwt
data:
  SYS.jwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJGVVZDSllLNk0zQUJQQkdGQjVNUUgzVDJPS0xPT0lHT0dWWjVUT1JVTlNLNVZBSUtSNDJBIiwiaWF0IjoxNjI4MjQzOTUwLCJpc3MiOiJPQkMzVjJYNlBISDMyMjJORlJEWjNTVlRTR1pBWEdXSENURDVFM0tWQTJBM01aVDI1QkVSUUNINiIsIm5hbWUiOiJTWVMiLCJzdWIiOiJBQkJTTVNHSU9TUFU0UUlINlJWRUhNRktWTVRFQ1RNWjMzRFBOVUZUTUlMTUw2VjY1WkNGQ0hYRSIsIm5hdHMiOnsibGltaXRzIjp7InN1YnMiOi0xLCJkYXRhIjotMSwicGF5bG9hZCI6LTEsImltcG9ydHMiOi0xLCJleHBvcnRzIjotMSwid2lsZGNhcmRzIjp0cnVlLCJjb25uIjotMSwibGVhZiI6LTF9LCJkZWZhdWx0X3Blcm1pc3Npb25zIjp7InB1YiI6e30sInN1YiI6e319LCJ0eXBlIjoiYWNjb3VudCIsInZlcnNpb24iOjJ9fQ.1Qyfof9ham4S-KdbLkHOSPKJnHU1waay1oQ1kl4wnPPFeO0QPaEpWRJ4_QNBnST_3FK1T18XbGnX2yWTB8NMCA

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-jwt
data:
  KO.jwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJhdWQiOiJPQkMzVjJYNlBISDMyMjJORlJEWjNTVlRTR1pBWEdXSENURDVFM0tWQTJBM01aVDI1QkVSUUNINiIsImV4cCI6MTk0Mzc3Njc1MCwianRpIjoiSU1QNlJGMlA0TVVTUE1VTERZRU5KNlRRWk5ZNkpGM0RGNldETlVXWTJWR1kzV1g3VFFNUSIsImlhdCI6MTYyODI0Mzk1MCwiaXNzIjoiT0JDM1YyWDZQSEgzMjIyTkZSRFozU1ZUU0daQVhHV0hDVEQ1RTNLVkEyQTNNWlQyNUJFUlFDSDYiLCJuYW1lIjoiS08iLCJuYmYiOjE2MjgyNDM5NTAsInN1YiI6Ik9CQzNWMlg2UEhIMzIyMk5GUkRaM1NWVFNHWkFYR1dIQ1RENUUzS1ZBMkEzTVpUMjVCRVJRQ0g2IiwibmF0cyI6eyJzaWduaW5nX2tleXMiOlsiT0JDM1YyWDZQSEgzMjIyTkZSRFozU1ZUU0daQVhHV0hDVEQ1RTNLVkEyQTNNWlQyNUJFUlFDSDYiXSwidHlwZSI6Im9wZXJhdG9yIiwidmVyc2lvbiI6Mn19.QmTUSEOKJAEtoZ6-RHIbps6ku4s5LbbeoSkNlZsW3sdTo9kQZrWubnHXT9XMHNmGCPGSkIWU7-FPFXrFBaFrCQ
